# Introduction to Logic {#introtologicfz}
Some _significant_ applications are demonstrated in this chapter.
## Logic and Deep Learning

Artificial intelligence is harder to describe in finite terms than are the algorithms we create that represent them. This is because it is fundamentally tied up with some of our deepest queries

What does it mean to be human?
What is the difference between humans and other animals?
Is there another species that is more intelligent than we are?
Will humans be surpassed by a more intelligent species?


The question as to whether these questions are valid or not is beyond the scope of this book but the questions themselves do provide us with a view into the history of logic.

Rene Descartes stated "Cogito, ergo sum" which translated means "I think therefore I am". He arrived at this statement after trying to use pure "reason" to find what was fundamentally true without any doubt. Although he couldn't complete his project, his value of "reason" was not unpopular and is gaining popularity in much of modern culture and can be heard in everyday conversations when we talk about the distinction between our thoughts and body. 

Reasoning starts with logic. 

Aristotle.

So let us begin with reasoning.

The branch and discipline titled logic was originally focused on finding absolute truths from statements that could be found in everyday discourse. Logic is fundamentally tied up with questions around how one can reason correctly. How one is able to deduce the correct answer given a set of statement or propositions.


What is the connection between logic and AI in history and maths?
Difference between propositional logic and symbolic logic
Where do we use logic in deep learning
Where does boolean logic end up ? In designing circuitsj

From propositional logic to boolean algebra
From Aristotle to George Boole to Claude Shannon

Books
Mathematical for Analysis of Logic
An Investigation of the Laws of Thought 


Propositions can be TRUE or FALSE
Propositions can be compounded
