---
title: "04-outline"
author: "Christian Ramsey"
date: "12/2/2018"
output: html_document
---

# Introduction
## Intro 

Whether it's been science, philosophy, or artificial intelligence, humans have always found ourselves at odds with our existences. Why do we exist? 

Many have tired to approach this question with varying degrees of illumination. It has been the main motivation for people to continuously push the boundry of science. 


But there are still more questions than there are answers. Artificial intelligence has become a salient mirror just as the industrial revolution made us realise what type of work "humans" can do and should be doing, and therefore illuminated what we valued as humans. 

We moved away from the endlessness of the question of why are we here and immediately moved to what Bourdieu called Distinction. What makes us different?

Of all the sciences that have begin to answer the question, progress in the field of philosophy, neurobiology, computer science, artificial intelligence, primatology, anthropology, and sociology have all played a role in thinning the line between us and others i.e. animals just as Netwonian physics have told us that we may not be alone, that we may not be the centre of the universe. Monkeys with tools, dolphins and casual sex, elephans and their endless memory, and the bees way of social organising shortened our view of humans as distinct.

But as Ernest Becker has said, we are half animal and half symbolic and so we find ourselves valuing what isseems more abstract and less grounded in the flesh. However, this won't stop us from searching the truth. 

Descarte and Aristole came to similar conclusion about the question. What makes us hman is reason, our ability to detached ourselves from our feelings and to rationalize. As Aristotle said, the essence of a man is to know and to desire to know. Man, by his rational intellect, is meant to seek truth and to understand the reality in which he exists. Aristotle regards our intellect as the way to define human.


Let's unpack this a little before we move on. Intellect would be considered as one crutial element of our 'mind' besides our intellect we also have will which is the ability to act. They work parallely to support our decision making. We use our ability to reason to help us distinguish right from wrong and to help us quickly adapt our behavior. We could be considered as one of most adaptive and flexible animals on earth. 


Our intellect also endows us the ability to manipulate symbols i.e. language. Our language and memory allow us to create and maintain the culture from one generation to another. 

But what is mind? We will in parallelle other scientists looked to Darwin and a more biological view of intelligence. 


As the studies on the nervous system became more and more advanceds, we moved from psychological theory grounded in observational research to looking  at networks of neurons and how they react to certain stimulus. This lead to neuroscience which was slowly uncovering that our central nervous system, i tthe key to our most profound features. Our cognition, thinking, reasoning, perceiving, emotion/feelings, and learning and memory. This would eventually lead to the cognitive revolution where many scientists from differing fields came to study the brain  and mental activitiy happeningin ourselves and other animals. It is obvious now, that this would lead to a want to emulate the central nervous system and . Can we emulate the brain and would that then give us keys to intelligence? Could that give us have conciousness an? AI seemed is an approach to answer such questions. We still no very little about how we reason an, learn, and experience everyday life. We can see AI as two tracks, applied AI, and philosophical AI. The first deals with cerating industrial applications and the second AIis around understanding intelligence. AI is both a tool and a mirror. So the hype will always exist because we do not know what makes us human and what we can and cannot emulate. AI has a chance at being a tool we use to make the world better or worse, and it also gives us a mirror into our world and what it means to exist. 




### Defining what makes us human.
### Neurobiology
### Philosophy
### Artificial Intelligence

## Thinking and Reasoning
### Logic
### Probability
### Symbolic AI & Expert Systems

## Neurobiology & Learning

### Learning Theory
### Behaviourism and Reinforcement Learning
### Artificial Neurons
### Cognitive Revolution

## AGI and it's discontents

### Definitions
### Safety & Ethics
### Consilience
### Pursuits

## Applied AI
### Cars
### Robots
### Voice Assistants
### Recommended 

## Conclusion
### What makes us human?
### Opportunities
