---
title: "Propositional Logic"
author: "hw"
date: "October 26, 2018"
output: html_document
---
> History of Propositional Logic 


#  Aristotle to George Boole 
* Logic was developed by Aristotle (384-322 BCE). He introduced the formal study of what is now known as 'formal logic', the logic that is concerned with the form, not the content, of statements or propositions. Basically, Aristotles system of logic introduced hypothetical syllogism, temporal model logic and the inductive logic. 

He holds that a propositon is a complex involving 2 terms, a subject and a predicate. Each of them are represented with a noun. The logic form of a proposition is determined by its quantity and by its quality. 

***
## Syllogism 
All Aristotle's logic revolves around one notion: the deduction (syllogism). Aristotle says: 
" A deduction is speech in which, certain things having been supposed, somehing different from those supposed results of necessity because of their being so."

Each of the 'things supposed' is a premise of the argument and what 'results of necessity' is the conclusion. 

***

Following Greek's tradition in logic, Cicero (106-43 BCE) introduced the term 'proposition' for which we will discuss in depth later. 
Alexander of Aphrodisias (3rd century A.D.) used the term 'logic' in the modern sense of distinguishing correct from incorrect reasoning. 

In the early twelfth centry, Peter Abelard wrote extensive commentaries attempting to articulate issues like opposition, conversion, opposition, quantity, and quality, and composed his treatise, 'the Dialectica'.

Later, William of Sherwood developed mnemonic verse as an aid in mastering the syllogisms. Jean Buridan elaborated a theory of conseqences which somewhere discussed the rules of inference.

Around the same time, Scholastic logician Raymond Lully used logic to prove the Christian faith. He also remarkably designed machines that would perform logical calculations, and is thus arguably considered as the father of computer programming.

# Early Modern Time 
In 1662, Antoine Am



## Branches of logics: 
1. Classical Logic - Aristotelian logic 
2. Symbolic Logic - Mathematical logic 

* Common Ground
"model symbolic logic is a development of the concepts and techniques which were implicit in the work of Aristotle.." - Bassoon and O'conner

In a sense, it agress that the modern symboloic logic is just a development and the extension of the concepts and techniques of Aristotlian logic. 

## Next Moves
### G.W Leibnitz (1646-1716)

He put forward a 2 fold plan that helped reform the logic. 
1. He suggested the establishment of a universal basic ideograms, in which all the scientific concepts could be represented by a combination of basic ideograms. 
2. he also suggested that a unversial calculus of reasoning could be devised which would provide an automatic method of solution for all problems which could be expressed in the universal language. 

### George Boole (1815-1864)
He formulated a system of algebra. Boole applied his algebra to several branches of logic including the syllogism of the classical logic. 
In turn, he showed that the Aristotelian syllogism which had been regarded as practically co-extensive with deductive logic could be shown to be a special case of kind of logical algebra.

What he did to replace Aristotelian syllogistic logic is by employing the numeral '1' for the universal class, the numeral '0' for the empty class, the multiplication notation 'xy' for the intersection of classes x and y, the addition 'x+y' for the union of classes x and y, etc. 

So that statements of syllogistic logic could be treated in quasi-mathematical fashion as equation: 
i.e. 'Not A or B' --> AB = 0

***
##Symbolic Logic 
Symbolic logi is by far the simplest kind of logic. It is the method of representing logical expression through the use of symbols and variables, rather than in ordinary language. 
***

> Propositional Logic 

# Definition: it is the most basic branch of mathematical logic. It is also called propositional calculus (PC).
It is a branch of logic that studies ways of joining and/or modifying entire propositions, statements or sentences to form more complicaed propositions, statements or sentences, as well as the logical relationships and properties that are derived from these methods of combining or altering statements.

In PC, the truth or falsity of a 'proposition' can be 'counted' determined using 'truth table'.


** Definition 3.1 **
"A declarative sentence in a sentence which is true or false, but not both, is called a Proposition (or statement). Statements which are exclamatory, interrogative or imperative in nature are not propositions.

Example: 
(1) 1 + 1 = 2 is a propostion while 1+1 is not a proposition 
(2) 1 + n = 2 is not a proposition either. We would instead call this kind of statement **propositional functions **
(3) Which color do you like the most?
(4) This flower is beautiful.
(5) Paris is the capital of France. 
(3) and (4) are not propositions since they are not declarative in nature. While (5) is a propositional statment since it is defined as a declarative sentence that is capable of having a truth value, such as being True or False.

If a proposition is True, we say that the truth value of the proposition is True denoted by T or 1;
If a proposition is False, the truth value will be False, denoted by F or 0.

## Atomic Propositions or primitive/simple sentence
It is the propostion which do not contain any of the logical operators or connectives i.e. Not, And, Or, If-the, If-and-Only-If)

## Compound Propositions or Molecular propositions
are those which contain one or more atomic statements using connectives 



> Perceptron 
## Perceving and recognizing automaton - Rossenplant (create perceptron : perceive and recognize patterns)

> neuro physiology
## Find Grandmather neurons Wiesel 


> Back Propagation 
## Control Theory - Henry Kelley 1960

> First working deep neural network 
## Ivakhnenko made first working neural network - 8 layers deep network 


>  First visual pattern recognition 
## Kunihiko 1969-80 recognize patten machine - visual pattern 
(hand-written)

> Hopfield Network 
## Recurrent Neural network -- memory system (1982)

> English Pronounce Machine 
## Pronounce english works -- 1885

> 1986
## Hinton - Learning Representation by Back-propagated errors (paper)


>1989
## LeCUnn make the machine recognize digits 
* Cash check by machine 

> 1989 Q-learning 

> 1993 thousand layer RNN 

> 1995 SVM  Vapnik (against deep learning)

> 1997 LSTM proposed 

> 1998 Gradient based learning by Yunn LeCunn (gradient based learning applied to document recognition)

> 2009 launch of Image net by Fei fei li 

> 2014 GANs GoodFellow + Yunn LeCunn

>


References: 
1. [Propositional Logic](file:///home/haohanlovesfanli/Downloads/PropositionalLogic.pdf)
2. [A short history of Logic](https://ourhappyschool.com/philosophy/short-history-logic)