---
title: "Propositional Logic"
author: "hw"
date: "October 26, 2018"
output: html_document
---

> History of Propositional Logic 


#  Aristotle to George Boole 
Logic was developed by Aristotle (384-322 BCE). He introduced the formal study of what is now known as 'formal logic', the logic that is concerned with the form, not the content, of statements or propositions. Basically, Aristotles system of logic introduced hypothetical syllogism, temporal model logic and the inductive logic. 

He holds that a propositon is a complex involving 2 terms, a subject and a predicate. Each of them are represented with a noun. The logic form of a proposition is determined by its quantity and by its quality. 

***
All Aristotle's logic revolves around one notion: the deduction (syllogism). Aristotle says: 
" A deduction is speech in which, certain things having been supposed, somehing different from those supposed results of necessity because of their being so."

Each of the 'things supposed' is a premise of the argument and what 'results of necessity' is the conclusion. 

***

Following Greek's tradition in logic, Cicero (106-43 BCE) introduced the term 'proposition' for which we will discuss in depth later. 
Alexander of Aphrodisias (3rd century A.D.) used the term 'logic' in the modern sense of distinguishing correct from incorrect reasoning. 

In the early twelfth centure, Peter Abelard wrote extensive commentaries attempting to articulate issues like opposition, conversion, opposition, quantity, and quality, and composed his treatise, 'the Dialectica'.

Later, William of Sherwood developed mnemonic verse as an aid in mastering the syllogisms. Jean Buridan elaborated a theory of conseqences which somewhere discussed the rules of inference.

Around the same time, Scholastic logician Raymond Lully used logic to prove the Christian faith. He also remarkably designed machines that would perform logical calculations, and is thus arguably considered as the father of computer programming.

# Medieval Logic 

Medieval Logic generally means the form of Aristotelian logic developed in medieval Occident throughout the period c. 1200-1600. 


# Traditional Logic 

It starts with Antonine Arnauld and Pierre Nicole's Logic, or the Art of Thinking published in 1662 or the Port Royal Logic in which the logic is defined as the 'art of managing one's reason right in the knowledge of things, both for the instruction of oneself and of others'. It was the most influential work on logic in England until John Stuart Mill's System of Logic in 1825.


Having invented calculus, Wilhelm Leibniz (1646-1716) concluded that the whole of logic actually depends on mathematics and thus worked on reducing scientific and philosophical speculation to computation. He also suggested that a unversial calculus of reasoning could be devised which would provide an automatic method of solution for all problems which could be expressed in the universal language. The current understanding of the power of Leibniz's discoveries did not emerge until the 1980s. 

#Modern and Contemporary Period  (1850 - Present)
During this period, logicians in the modern period 'rediscovered' the Stoic logic of proposition. 

People like Augustus De Morgan (1806-1864) proposed some theorem in that logic which now bear his name. 
Considered the founder of symbolic logic and Boolean Algebra, which is the basis of all modern computer arithmetic. 

George Boole (1815-1864) gave us Boolean Logic which treats propositions as either true or false. His use of numbers to express the truth values of compound statements have significantly influenced the development of computers and he is regarded as being one of the founders of the field of computer science. Until today, programmers still use his principle to test the trugh of program results or user feedback. 
 
John Venn (1834-1923) was a Cambridge logician who published 3 standard texts in logic, *The Logic of Chance 1866*, *symbolic Logic* 1881, and *The Principles of Empirical Logic* 1889. He is remembered for introducing the circular diagrams as a tool to test the validity of syllogisms, known as Venn Diagrams. 

Around the same time, John Stuart Mill (1806-1873) made a thorough study about inductive reasoning and introduced methods for checking such arguments now known as 'Mill's Methods'. And Charles Sanders Peirce (1839-1914) introduced Pragmatism, at the core of which he argued that ideas should be evaluated solely by their practical effects and not by any intrinsic qualities of reason or logic. 


Gottlob Frege (1848-1925) pronounced that logic is the basis of methematics and that arithmetic and analysis are part of logic. He has been called the greatest logician since Aristotle. By developing the predicate calculus (Quantification Theory), he had combined Aristotelian and Stoic's logics and his work was the foundation or beginning point for an enormous outpouring of work in formal logic. 

In 1903, Bertrand Russell (1872-1970) started his project 'The Principles of Mathematics' in which he purposed to prove that 'all pure mathematics deals exclusively with concepts definable in terms of a very small number of logic principles.' Russel also continued the development of the predicate calculus and he alos found the inconsistency in Ferge's system (because Russell's Paradox could be derived within Frege's system).


The next wave of the logic can be called the 'mathematical school'. This tradition or school includes the work of Richard Dedekind (1831-1916), Giuseppe Peano (1858-1932), David Hibert (1862-1943). Ernst Zermelo (1871-1953), and many ohter since then. Its goal was the axiomatization of particular branches of mathematics, including geometry, arithetic, analysis, and set theory. 

In 1889 Peano published the first version of the logical axiomatization of arithmetic. Five of the nine axioms he came up with are now known as the Peano axioms. One of these axioms was a formalized statement of the principle of mathematical induction.


Ernst Zermelo's axiomatic set theory was also an attempt to escape Russell's Paradox. His axioms went well beyond Frege's axioms of extensionality and unlimited set abstraction, and evolved into the now-canonical Zermelo-Fraenkel set theory. 

Gradually, logic became the branch of mathematics that was to be brought within the axiomatic methodology. Jan Lukasiewicz worked on multi-valued logics. His three-valued propositional calculus, introduced in 1917, was the first explicitly axiomatized non-classical logical calculus.


The famous Ludwig Wittgenstein (1819-1951) entered the list of significant logician by being oen of the developers of the 'truth tables'. 


This intensive work on mathematical issues culminated in the work of Kurt Godel (1906-1978), a logician of the caliber of Aristotle and Frege. Using many applications of the rules of logic, Kurt Godel proved his 'incompleteness theorem', which proposes that some parts of mathematics are based on ideas that cannot be proved within the system of mathematics. 

Godel was also one of the central figures in the study of computability. Others included Alonzo Church (1903-1995), Alan Turing (1912-1954), and others. 


There are plenty of other advances in logic. Logical empiricist [Rudolph Carnap]() (1891-1970) was associated with the famous verfiability principle, according to which a synthetic statement is meaninful only if it is verificable. 

Logical positivist [A.J. Ayer](), on the other hand, wrote in 1936 his 'Language, Truth, and Logic' in which he focused on the role of language as the medium through which knowledge is understood and verified. 

In 1965, [Lofti Zadeh]() developed 'fuzzy logic' which allows imprecise answers to questions in addition to being either clear-cut true or false. This logic now serves as the basis of computer programming designed to mimic human intelligence. 

## Branches of logics: 
1. Classical Logic - Aristotelian logic 
2. Symbolic Logic - Mathematical logic 

* Common Ground
"model symbolic logic is a development of the concepts and techniques which were implicit in the work of Aristotle.." - Bassoon and O'conner

In a sense, it agress that the modern symboloic logic is just a development and the extension of the concepts and techniques of Aristotlian logic. 

## Next Moves
### G.W Leibnitz (1646-1716)

He put forward a 2 fold plan that helped reform the logic. 
1. He suggested the establishment of a universal basic ideograms, in which all the scientific concepts could be represented by a combination of basic ideograms. 
2. he also suggested that a unversial calculus of reasoning could be devised which would provide an automatic method of solution for all problems which could be expressed in the universal language. 

### George Boole (1815-1864)
He formulated a system of algebra. Boole applied his algebra to several branches of logic including the syllogism of the classical logic. 
In turn, he showed that the Aristotelian syllogism which had been regarded as practically co-extensive with deductive logic could be shown to be a special case of kind of logical algebra.

What he did to replace Aristotelian syllogistic logic is by employing the numeral '1' for the universal class, the numeral '0' for the empty class, the multiplication notation 'xy' for the intersection of classes x and y, the addition 'x+y' for the union of classes x and y, etc. 

So that statements of syllogistic logic could be treated in quasi-mathematical fashion as equation: 
i.e. 'Not A or B' --> AB = 0

***
##Symbolic Logic 
Symbolic logi is by far the simplest kind of logic. It is the method of representing logical expression through the use of symbols and variables, rather than in ordinary language. 
***

> Propositional Logic 

# Definition: it is the most basic branch of mathematical logic. It is also called propositional calculus (PC).
It is a branch of logic that studies ways of joining and/or modifying entire propositions, statements or sentences to form more complicaed propositions, statements or sentences, as well as the logical relationships and properties that are derived from these methods of combining or altering statements.

In PC, the truth or falsity of a 'proposition' can be 'counted' determined using 'truth table'.


** Definition 3.1 **
"A declarative sentence in a sentence which is true or false, but not both, is called a Proposition (or statement). Statements which are exclamatory, interrogative or imperative in nature are not propositions.

Example: 
(1) 1 + 1 = 2 is a propostion while 1+1 is not a proposition 
(2) 1 + n = 2 is not a proposition either. We would instead call this kind of statement **propositional functions **
(3) Which color do you like the most?
(4) This flower is beautiful.
(5) Paris is the capital of France. 
(3) and (4) are not propositions since they are not declarative in nature. While (5) is a propositional statment since it is defined as a declarative sentence that is capable of having a truth value, such as being True or False.

If a proposition is True, we say that the truth value of the proposition is True denoted by T or 1;
If a proposition is False, the truth value will be False, denoted by F or 0.

## Atomic Propositions or primitive/simple sentence
It is the propostion which do not contain any of the logical operators or connectives i.e. Not, And, Or, If-the, If-and-Only-If)

## Compound Propositions or Molecular propositions
are those which contain one or more atomic statements using connectives 




References: 
1. [Propositional Logic](file:///home/haohanlovesfanli/Downloads/PropositionalLogic.pdf)
2. [A short history of Logic](https://ourhappyschool.com/philosophy/short-history-logic)