---
title: Logic & Reasoning
description: |
  Edited version of logic
date: "`r Sys.Date()`"
output: radix::radix_article
---

# Introduction
## Defining and redefining what makes us human
 

Whether it's been science, philosophy, or artificial intelligence, humans have always found ourselves at odds with our existences. Why do we exist? 

Many have tired to approach this question with varying degrees of illumination. It also fuels us to continuously push the boundry of science to uncover the truth of the world and ourselves. 


But there are still more questions than there are answers. Artificial intelligence has become a salient mirror just as the industrial revolution made us realise what type of work "humans" can do and should be doing, and therefore illuminates what we valued as humans. 

We moved away from the endlessness of the question of why are we here and immediately moved to what Bourdieu called Distinction. 

> What makes us different?

Of all the sciences that have begin to answer the question, progress in the field of philosophy, neurobiology, computer science, artificial intelligence, primatology, anthropology, and sociology have all played a role in thinning the line between us and others i.e. animals just as Netwonian physics have told us that we may not be alone, that we may not be the centre of the universe. Monkeys with tools, dolphins and casual sex, elephans and their endless memory, and the bees way of social organising shortened our view of humans as distinct.

But as Ernest Becker has said, we are half animal and half symbolic and so we find ourselves valuing what is seems more abstract and less grounded in the flesh. However, despite the complexity of the issue, it never discourages us from seeking the truth. 

### Philosophy

Descarte and Aristole came to similar conclusion about the question. What makes us human is our ability to reason, to detached ourselves from our feelings and to rationalize. As Aristotle said,*the essence of a man is to know and to desire to know. Man, by his rational intellect, is meant to seek truth and to understand the reality in which he exists.* 

Our intellect also endows us the ability to manipulate symbols i.e. language. Our language and memory allow us to create and maintain the culture from one generation to another. It certainly discriminate us from other species.

However, it does not fully solve our problems. We are certainly more than just our intellect.

More precisely, some scientists may argue intellect could be considered as one crutial element of the 'Mind'. Alongside intellect, we also have our human 'will' which illumates our ability to choose and to act. They work parallely to support our decision making. We use our ability to reason, to distinguish right from wrong, and to quickly adapt our behavior in a novel environment. We could be considered as one of most adaptive and flexible animals on earth. 


### Neurobiology

But what is mind? We will in parallel other scientists looked to Darwin and a more biological view of intelligence.

As the studies on the nervous system became more and more advances, we moved from psychological theory grounded in observational research to looking at networks of neurons and how they react to certain stimulus. This leads to neuroscience which was slowly unearthing the mechanism and the power of our central nervous system, the key to our most profound features i.e. our cognition, thinking, reasoning, perceiving, emotion/feelings, and learning and memory. 

This would eventually lead to the cognitive revolution where the scientists from different fields came to study the brain and mental activitiy happening in ourselves and other animals. It is obvious now, that this would lead to a want to emulate the central nervous system and possibly cultivate intelligence from there. 


### The rise of Artificial Intelligence

Can we emulate the brain and would that then give us keys to intelligence? Could that give us the answer to conciousness? 

AI seemed as an adaquate approach to answer such questions. We still only know very little about how we reason, learn, and experience everyday life. By applying and experimenting our learning with AI, we harvest a swifter progress towards the truth of intelligence. 

At the current consilience point of the history, we can see AI as two tracks, **applied AI**, and **philosophical AI**. The former deals with cerating industrial applications to benefit us and the latter is around understanding and breeding intelligence. 


It now becomes clear for us that AI is both a tool and a mirror. The hype will always exist because we do not know what makes us human and what we can and cannot emulate. AI has a chance at being a tool we can use to make the world better or worse, and it also gives us a mirror into ourselves, the mystery of intelligence and what it means to exist. 



## Thinking and Reasoning
### Logic
Logic and AI has a long and interwined history. Dating back to 300 BC through to the present, there have been major figures across diverse fields as philosophy, sociology, economics, and mathematics that have looked to reasoning as a way of distinguising their discipline and grounding their philosophy. Many then and now see logic as the key to elevating man from lowly animal towards the higher reaches of the purely symbolic or intellectual man. The formalisation of logic began with Aristotle's Oregano. 

[Aristotle](https://en.wikipedia.org/wiki/Aristotle) (384-322 BCE), as one of the pioneers of reasoning, he set out to conduct the formal study of what is now known as 'formal logic'. He was convinced that we were equal in every way to other animals but we maintained an element that they do not, and this element was none other than rationality. This is most notably viewed in his treatise, On the Soul, where he said that man is animal + rationale. Aristotle's formal logic would begin with the syllogism, which was found in his collected works entitled the Organon.

In 1275, Ramon Llull, a spanish Theologian wrote the Ars Magna (Art of Finding Truth), which provided a method based in logic to produce new knowledge.
 
 %connectedback to labniz
 
Followed their footstep, Rene Descartes also came up with one of the best-known quotations in philosophy:"Cogito, ergo sum" ("I think, therefore I am"). Besides being a 'rational' philosopher, his contribution to mathematics was also of the first order, he is the inventor of Cartesian coordinate system and the founder of analytics geometry which has laid the foundation of the later developed calculus and mathematical analysis.=

%Charles Babbage 

%add the even pf rene insteadof thesummary 

[Gottfried Wilhelm Leibniz](https://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz) (1646-1716), along with Rene Descartes, Leibiniz was a major figure in the Rationalism movement. His contributions to logic were perhaps the most important between Aristotle and the later extended model of symbolic logic. As the inventor of calculus, and the discoverer of the binary system. He suggested that a universal calculus of reasoning could be devised which would provide an automatic method of solution for all problems which could be expressinged in the universal language. This was one of the most profound views of  endowing mathematics with the ability to mechanise human thought. This would be extended through to machines. 


%add tje principle of mathematics 

Symbolic logic was not fully developed until the invention of Boolean Algebra. As the inventor of the Boolean Algebra, [George Boole](https://en.wikipedia.org/wiki/George_Boole) (1815-1864) is also a philosopher and logician who proposed that:
> No general method for the solution of questions in the theory of probabilities can be established which does not explicitly recognise, not only the special numerical bases of the science, but also those universal laws of thought which are the basis of all reasoning, and which, whatever they may be as to their essence, are at least mathematical as to their form.

After George Boole, plenty of other well-known logician and mathematicians joined the force to push the development of logic and helped to establish the unshakable status of logic as one of the most important properties of human. 

%discovery vs Inventiom

[Gottlob Frege](https://en.wikipedia.org/wiki/Gottlob_Frege) (1848-1925) %discovered predicate logic. He is well-acknowledged by many to be the father of analytic philosophy, concentrating on the philosophy of language and mathematics. His work was later brought to the center of the attention by Giuseppe Peano (1858–1932) and Bertrand Russell (1872–1970) and served as the beginning point for an enormous outpouring of work in formal logic. 

As the inventor of Turing machine and famous Turing test, [Alan Turing](https://en.wikipedia.org/wiki/Alan_Turing) is widely considered to be the father of theoretical computer science and artificial intelligence. The Turing machine that he designed is a mathematical model of computation which is capable of simulating that algorithm's logic can be constructed.

%rewrite the alanturing story and events and highly correlatedwith logic 

Claude Shannon (1916-2001) is noted for having founded information theory with a landmark paper, A Mathematical Theory of Communication, that he published in 1948. He is, perhaps, equally well known for founding digital circuit design theory in 1937, when—as a 21-year-old master's degree student at the Massachusetts Institute of Technology (MIT)—he wrote his thesis demonstrating that electrical applications of Boolean algebra could construct any logical numerical relationship

All of those people have brought logic to life and step by step helped the invention of the early computer and the birth of AI. 


### Probability

### Symbolic AI & Expert Systems

> A physical symbol system has the necessary and sufficient means for general intelligent action." - Allen Newell and Herbert A. Simon

#### This is a quote from Allen Newell and Herbert Simon's "" is called "the physical symbol systems hypothesis".  

> The hypothesis [is] that intelligence is the work of symbol systems. Stated a little more formally, the hypothesis is that a physical symbol system ... has the necessary and sufficient means for general intelligent action. - Herbert Simon, The Sciences of the Artificial

#### Herbert Simon and Allen Newell worked on symbolic systems 

> A physical symbol system holds a set of entities, called symbols. These are physical patterns (e.g., chalk marks on a blackboard) that can occur as components of symbol structures. In the case of computers, a symbol system also possesses a number of simple processes that operate upon symbol structures - processes that create, modify, copy and destroy symbols. A physical symbol system is a machine that, as it moves through time, produces an evolving collection of symbol structures. Symbol structures can, and commonly do, sever as internal representations (e.g., "mental images") of the environment to which the symbol system is seeking to adapt. They allow it to model that environment with greater or less veridicality and in greater or less detail, and consequently to reason about it. Of course, for this capability to be of any use to the symbol system, it must have windows on the world and hands, too. It must have means for acquiring information from the external environment that can be encoded into internal symbols, as well as means for producing symbols that initiate action upon the environment. Thus it must use symbols to designate objects and relations and actions in the world external to the system,

#### Expert systems

####The physical symbol systems hypothesis []

#### Alan Turing and Alonzo Church - Church–Turing thesis

#### Separating knowledge from inference

#### Judea Pearl and causal reasoning

#### Symbolic AI and The Chinese room
#### Searle posited that 

#### Gary Marcus and Yann Lecunn and neuro-symbolic AI

### Computation


## Neurobiology & Learning

### Learning Theory
### Behaviourism and Reinforcement Learning
### Artificial Neurons
### Cognitive Revolution

## AGI and it's discontents

### Definitions
### Safety & Ethics
### Consilience
### Pursuits

## Applied AI
### Cars
### Robots
### Voice Assistants
### Recommended 

## Conclusion
### What makes us human?
### Opportunities
